example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from wishlist import views, urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('xml/', views.show_xml, name='show_xml'),
    path('json/', views.show_json, name='show_json'),
    path('xml/<int:id>', views.show_xml_by_id, name='how_xml_by_id'),
    path('json/<int:id>', views.show_json_by_id, name='show_json_by_id'), 
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_ajax
from wishlist.views import show_wishlist, show_xml, show_json, show_xml_by_id, show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import create_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', create_wishlist, name='create_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Amanda Christie Tarigan',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
    'nama': 'Amanda Christie Tarigan',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, 'wishlist_ajax.html', context)

@login_required(login_url='/wishlist/login/')
def create_wishlist(request):
    if request.method == 'POST':
        newItem = BarangWishlist(
            nama_barang=request.POST.get('nama_barang'),
            harga_barang=request.POST.get('harga_barang'),
            deskripsi=request.POST.get('deskripsi'),
        )
        newItem.save()
    return HttpResponseRedirect(reverse('wishlist:show_wishlist_ajax'))

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

wishlist/templates/login.html
<html>
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>

<body>
    <div class="items">
        <div class = "login">
            <div class="card-body">
            
            <h1>Login</h1>
            <form method="POST" action="">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Username </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Password </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                </table>
                
                <center><input class="btn button" type="submit" value="Login"></center>
            </form>

            {% if messages %}
                {% for message in messages %}
                    <p class="message">{{ message }}</p>
                {% endfor %}
            {% endif %}     
                
            <p>Don't have an account yet? <b><a href="{% url 'wishlist:register' %}">Sign up!</a></b></p>

            </div>
        </div>
    </div>

</body>
{% endblock content %}
</html>

wishlist/templates/register.html
<html>
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'register.css' %}">
</head>

<body>
    <div class="items">
        <div class="card-body">
            
            <h1>Registration</h1>  

                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}
                    </table> 
                    <center><input class="btn button" type="submit" name="submit" value="Sign Up"/> </center>
                </form>

            {% if messages %}    
                {% for message in messages %}  
                    <p class="message">{{ message }}</p>
                {% endfor %}  
            {% endif %}

        </div> 
    </div> 
</body>
{% endblock content %}
</html>

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <div class="container-fluid">
      <a class="navbar-brand">{{nama}}</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/wishlist/xml/">XML</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/wishlist/json/">JSON</a>
          </li>
        </ul
        <button class="btn btn-outline-success" type="submit"></button>
        <a href="/wishlist/logout/" class="btn btn-outline-success">Logout</a></button>
      </div>
    </div>
  </nav>

<br>
<h1 class="text-center"> 🛍️ My Wishlist 🛍️ </h1>
<table class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th scope="col" class="align-middle text-center">Nama Barang</th>
            <th scope="col" class="align-middle text-center">Harga Barang</th>
            <th scope="col" class="align-middle text-center">Deskripsi</th>
        </tr>
    </thead>

    <tbody class="table-group-divider">
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <td>{{barang.nama_barang}}</td>
            <td>{{barang.harga_barang}}</td>
            <td>{{barang.deskripsi}}</td>
        </tr>
    {% endfor %}
    </tbody>

</table>
<p>Sesi terakhir login: {{ last_login }}</p>

</div>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        get_data();
        $( "added-data" ).submit(function( event ) {
            event.preventDefault();

            var actionurl = event.currentTarget.action;

            $.ajax({
                    url: actionurl,
                    type: 'post',
                    dataType: 'json',
                    data: $("added-data").serialize(),
                    success: function(data) {
                        var tr = $("<tr></tr>");
                        for (const [key, value] of Object.entries(data)) {
                            var td = $("<td></td>").html(value);
                            tr.append(td);
                        }
                        $("#tabel-wishlist").append(tr);
                    },
                    error: function(){
                        alert("ERROR");
                    }
            });
        });
    });

    function get_data() {
        $.get("../json", function(data) {
            data.forEach(element => {
                var tr = $("<tr></tr>");
                for (const [key, value] of Object.entries(element.fields)) {
                    var td = $("<td></td>").html(value);
                    tr.append(td);
                }
                $("#tabel-wishlist").append(tr);
            });
        });
    }
</script>
{% endblock meta %}

{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'wishlist_ajax.css' %}">
</head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
        <div class="container-fluid">
        <a class="navbar-brand">{{nama}}</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/wishlist/xml/">XML</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/wishlist/json/">JSON</a>
            </li>
            </ul
            <button class="btn btn-outline-success" type="submit"></button>
            <a href="/wishlist/logout/" class="btn btn-outline-success">Logout</a></button>
        </div>
        </div>
  </nav>


<br>
<h1> 🛍️ My Wishlist 🛍️ </h1>

<table id="tabel-wishlist" class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th scope="col" class="align-middle text-center">Nama Barang</th>
            <th scope="col" class="align-middle text-center">Harga Barang</th>
            <th scope="col" class="align-middle text-center">Deskripsi</th>
        </tr>
    </thead>
    <tbody class="table-group-divider"></tbody>
</table>

<p>Sesi terakhir login: {{ last_login }}</p>

<div class="card-body">
    <h1>Create New Wishlist</h1>
    <form method="POST" action="{% url 'wishlist:create_wishlist' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>Nama Barang</td>
                <td><input type="text" name="nama_barang" placeholder="nama barang" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Harga Barang</td>
                <td><input type="text" name="harga_barang" placeholder="harga barang" class="form-control"></td>
            </tr>
            <tr>
                <td>Deskripsi</td>
                <td><input type="text" name="deskripsi" placeholder="deskripsi" class="form-control"></td>
            </tr>
        </table>
        
        <center><input class="button" type="submit" value="Add Wishlist"></center>
    </form>
</div>

{% endblock content %}